server:
  port: 8052
spring:
  application:
    name: admin-server
feign:
  sentinel:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true